/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int ABSTRACT = 7;
  int BOOLEAN = 8;
  int BREAK = 9;
  int BYTE = 10;
  int CASE = 11;
  int CATCH = 12;
  int CHAR = 13;
  int CLASS = 14;
  int CONST = 15;
  int CONTINUE = 16;
  int DEFAULTCASE = 17;
  int DO = 18;
  int DOUBLE = 19;
  int ELSE = 20;
  int EXTENDS = 21;
  int FALSE = 22;
  int FINAL = 23;
  int FINALLY = 24;
  int FLOAT = 25;
  int FOR = 26;
  int GOTO = 27;
  int IF = 28;
  int IMPLEMENTS = 29;
  int IMPORT = 30;
  int INSTANCEOF = 31;
  int INT = 32;
  int INTERFACE = 33;
  int LONG = 34;
  int NATIVE = 35;
  int NEW = 36;
  int NULL = 37;
  int PACKAGE = 38;
  int PRIVATE = 39;
  int PROTECTED = 40;
  int PUBLIC = 41;
  int RETURN = 42;
  int SHORT = 43;
  int STATIC = 44;
  int STRICTFP = 45;
  int SUPER = 46;
  int SWITCH = 47;
  int SYNCHRONIZED = 48;
  int THIS = 49;
  int THROW = 50;
  int THROWS = 51;
  int TRANSIENT = 52;
  int TRUE = 53;
  int TRY = 54;
  int VOID = 55;
  int VOLATILE = 56;
  int WHILE = 57;
  int PLUS = 58;
  int ASSIGN = 59;
  int DEC = 60;
  int EQUAL = 61;
  int GT = 62;
  int INC = 63;
  int LAND = 64;
  int LE = 65;
  int LNOT = 66;
  int MINUS = 67;
  int PLUS_ASSIGN = 68;
  int STAR = 69;
  int DIV = 70;
  int REM = 71;
  int ASL = 72;
  int ASR = 73;
  int LSR = 74;
  int BNOT = 75;
  int BIOR = 76;
  int BXOR = 77;
  int BAND = 78;
  int QM = 79;
  int LNOT_EQUAL = 80;
  int GE = 81;
  int LT = 82;
  int LOR = 83;
  int DIV_ASSIGN = 84;
  int MINUS_ASSIGN = 85;
  int STAR_ASSIGN = 86;
  int REM_ASSIGN = 87;
  int ASR_ASSIGN = 88;
  int LSR_ASSIGN = 89;
  int ASL_ASSIGN = 90;
  int BXOR_ASSIGN = 91;
  int BIOR_ASSIGN = 92;
  int BAND_ASSIGN = 93;
  int LPAREN = 94;
  int RPAREN = 95;
  int LCURLY = 96;
  int RCURLY = 97;
  int LBRACK = 98;
  int RBRACK = 99;
  int SEMI = 100;
  int COMMA = 101;
  int DOT = 102;
  int COLON = 103;
  int IDENTIFIER = 104;
  int LETTER = 105;
  int DIGIT = 106;
  int NON_ZERO_DIGIT = 107;
  int INT_LITERAL = 108;
  int DOUBLE_LITERAL = 109;
  int CHAR_LITERAL = 110;
  int STRING_LITERAL = 111;
  int ESC = 112;
  int ERROR = 113;
  int MULTI_LINE_COMMENT = 7;
  int ABSTRACT = 8;
  int BOOLEAN = 9;
  int BREAK = 10;
  int BYTE = 11;
  int CASE = 12;
  int CATCH = 13;
  int CHAR = 14;
  int CLASS = 15;
  int CONST = 16;
  int CONTINUE = 17;
  int DEFAULTCASE = 18;
  int DO = 19;
  int DOUBLE = 20;
  int ELSE = 21;
  int EXTENDS = 22;
  int FALSE = 23;
  int FINAL = 24;
  int FINALLY = 25;
  int FLOAT = 26;
  int FOR = 27;
  int GOTO = 28;
  int IF = 29;
  int IMPLEMENTS = 30;
  int IMPORT = 31;
  int INSTANCEOF = 32;
  int INT = 33;
  int INTERFACE = 34;
  int LONG = 35;
  int NATIVE = 36;
  int NEW = 37;
  int NULL = 38;
  int PACKAGE = 39;
  int PRIVATE = 40;
  int PROTECTED = 41;
  int PUBLIC = 42;
  int RETURN = 43;
  int SHORT = 44;
  int STATIC = 45;
  int STRICTFP = 46;
  int SUPER = 47;
  int SWITCH = 48;
  int SYNCHRONIZED = 49;
  int THIS = 50;
  int THROW = 51;
  int THROWS = 52;
  int TRANSIENT = 53;
  int TRUE = 54;
  int TRY = 55;
  int VOID = 56;
  int VOLATILE = 57;
  int WHILE = 58;
  int PLUS = 59;
  int ASSIGN = 60;
  int DEC = 61;
  int EQUAL = 62;
  int GT = 63;
  int INC = 64;
  int LAND = 65;
  int LE = 66;
  int LNOT = 67;
  int MINUS = 68;
  int PLUS_ASSIGN = 69;
  int STAR = 70;
  int DIV = 71;
  int REM = 72;
  int ASL = 73;
  int ASR = 74;
  int LSR = 75;
  int BNOT = 76;
  int BIOR = 77;
  int BXOR = 78;
  int BAND = 79;
  int QM = 80;
  int LNOT_EQUAL = 81;
  int GE = 82;
  int LT = 83;
  int LOR = 84;
  int DIV_ASSIGN = 85;
  int MINUS_ASSIGN = 86;
  int STAR_ASSIGN = 87;
  int REM_ASSIGN = 88;
  int ASR_ASSIGN = 89;
  int LSR_ASSIGN = 90;
  int ASL_ASSIGN = 91;
  int BXOR_ASSIGN = 92;
  int BIOR_ASSIGN = 93;
  int BAND_ASSIGN = 94;
  int LPAREN = 95;
  int RPAREN = 96;
  int LCURLY = 97;
  int RCURLY = 98;
  int LBRACK = 99;
  int RBRACK = 100;
  int SEMI = 101;
  int COMMA = 102;
  int DOT = 103;
  int COLON = 104;
  int IDENTIFIER = 105;
  int LETTER = 106;
  int DIGIT = 107;
  int NON_ZERO_DIGIT = 108;
  int INT_LITERAL = 109;
  int CHAR_LITERAL = 110;
  int STRING_LITERAL = 111;
  int ESC = 112;
  int ERROR = 113;
  int MULTI_LINE_COMMENT = 7;
  int ABSTRACT = 8;
  int BOOLEAN = 9;
  int BREAK = 10;
  int BYTE = 11;
  int CASE = 12;
  int CATCH = 13;
  int CHAR = 14;
  int CLASS = 15;
  int CONST = 16;
  int CONTINUE = 17;
  int DEFAULTCASE = 18;
  int DO = 19;
  int DOUBLE = 20;
  int ELSE = 21;
  int EXTENDS = 22;
  int FALSE = 23;
  int FINAL = 24;
  int FINALLY = 25;
  int FLOAT = 26;
  int FOR = 27;
  int GOTO = 28;
  int IF = 29;
  int IMPLEMENTS = 30;
  int IMPORT = 31;
  int INSTANCEOF = 32;
  int INT = 33;
  int INTERFACE = 34;
  int LONG = 35;
  int NATIVE = 36;
  int NEW = 37;
  int NULL = 38;
  int PACKAGE = 39;
  int PRIVATE = 40;
  int PROTECTED = 41;
  int PUBLIC = 42;
  int RETURN = 43;
  int SHORT = 44;
  int STATIC = 45;
  int STRICTFP = 46;
  int SUPER = 47;
  int SWITCH = 48;
  int SYNCHRONIZED = 49;
  int THIS = 50;
  int THROW = 51;
  int THROWS = 52;
  int TRANSIENT = 53;
  int TRUE = 54;
  int TRY = 55;
  int VOID = 56;
  int VOLATILE = 57;
  int WHILE = 58;
  int PLUS = 59;
  int ASSIGN = 60;
  int DEC = 61;
  int EQUAL = 62;
  int GT = 63;
  int INC = 64;
  int LAND = 65;
  int LE = 66;
  int LNOT = 67;
  int MINUS = 68;
  int PLUS_ASSIGN = 69;
  int STAR = 70;
  int DIV = 71;
  int REM = 72;
  int ASL = 73;
  int ASR = 74;
  int LSR = 75;
  int BNOT = 76;
  int BIOR = 77;
  int BXOR = 78;
  int BAND = 79;
  int QM = 80;
  int LNOT_EQUAL = 81;
  int GE = 82;
  int LT = 83;
  int LOR = 84;
  int DIV_ASSIGN = 85;
  int MINUS_ASSIGN = 86;
  int STAR_ASSIGN = 87;
  int REM_ASSIGN = 88;
  int ASR_ASSIGN = 89;
  int LSR_ASSIGN = 90;
  int ASL_ASSIGN = 91;
  int BXOR_ASSIGN = 92;
  int BIOR_ASSIGN = 93;
  int BAND_ASSIGN = 94;
  int LPAREN = 95;
  int RPAREN = 96;
  int LCURLY = 97;
  int RCURLY = 98;
  int LBRACK = 99;
  int RBRACK = 100;
  int SEMI = 101;
  int COMMA = 102;
  int DOT = 103;
  int COLON = 104;
  int IDENTIFIER = 105;
  int LETTER = 106;
  int DIGIT = 107;
  int NON_ZERO_DIGIT = 108;
  int INT_LITERAL = 109;
  int CHAR_LITERAL = 110;
  int STRING_LITERAL = 111;
  int ESC = 112;
  int ERROR = 113;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"!\"",
    "\"-\"",
    "\"+=\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"~\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"?\"",
    "\"!=\"",
    "\">=\"",
    "\"<\"",
    "\"||\"",
    "\"/=\"",
    "\"-=\"",
    "\"*=\"",
    "\"%=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"<<=\"",
    "\"^=\"",
    "\"|=\"",
    "\"&=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
